#!/usr/bin/env python
# Movie-Script is a Script Use in Hacking Movies 
# By Yehia Mamdouh - twitter.com/@Yehia1mamdouh / Facebook/yehia.mamdouh.98

import colorama
from colorama import Fore, Back, Style
import time
import sys
from time import sleep
print '\033[1m'
print ""
print Fore.GREEN +  "Warning:-- System Vulnerable "


toolbar_width = 50

# setup toolbar
hota = "System Cracking"

from tqdm import *
print ""
print Fore.CYAN + "System Cracking"
print ""
for i in tqdm(range(10)):
	time.sleep(2)

print ""
print Fore.RED + "Access Granted"

print ""
print Fore.CYAN + "LOcate Traget Files"
print "############### Complete"
print ""
print Fore.CYAN + "Excute Cryto Operations"
print "############### Complete"

print ""
sys.stdout.write("Encrypting --> /bin: ")
sys.stdout.flush()
some_list = [0] * 101
for idx, item in enumerate(some_list):
    msg = "Percentage %i of %i" % (idx, len(some_list)-1)
    sys.stdout.write(msg + chr(8) * len(msg))
    sys.stdout.flush()
    sleep(0.1)

print ""

sys.stdout.write("Encrypting --> /sys: ")
sys.stdout.flush()
some_list = [0] * 101
for idx, item in enumerate(some_list):
    msg = "Percentage %i of %i" % (idx, len(some_list)-1)
    sys.stdout.write(msg + chr(8) * len(msg))
    sys.stdout.flush()
    sleep(0.1)

print ""

sys.stdout.write("Encrypting --> /etc: ")
sys.stdout.flush()
some_list = [0] * 101
for idx, item in enumerate(some_list):
    msg = "Percentage %i of %i" % (idx, len(some_list)-1)
    sys.stdout.write(msg + chr(8) * len(msg))
    sys.stdout.flush()
    sleep(0.1)

print ""

sys.stdout.write("Encrypting --> /root: ")
sys.stdout.flush()
some_list = [0] * 101
for idx, item in enumerate(some_list):
    msg = "Percentage %i of %i" % (idx, len(some_list)-1)
    sys.stdout.write(msg + chr(8) * len(msg))
    sys.stdout.flush()
    sleep(0.1)

print ""

print Fore.RED + "You Have Been Hacked"
